### ISSUE TITLE
OK to convert tabs to spaces in tests?

### ISSUE THREAD

**Issue by matthew-brett** [afraenkel/babypandas#7]
Unlike the main code, and [contrary to PEP8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces), the tests use tabs for indentation.   I think most of us have editors set up to follow PEP8, and use spaces.   Do you mind if I convert the tabs to spaces, in a PR?

**Comment by matthew-brett** [comment]
I went ahead and did the PR...

**Comment by afraenkel** [comment]
Merged
